sonar.projectKey=flask-todo
sonar.projectName=flask-todo

sonar.sources=app.py
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=.venv/**,instance/**,__pycache__/**,.pytest_cache/**,.sonar/**,.git/**

sonar.sourceEncoding=UTF-8

sonar.python.version=3.12