sonar.projectKey=flask-todo-local
sonar.projectName=flask-todo
sonar.sources=.
sonar.tests=tests
sonar.exclusions=.venv/**,instance/**,__pycache__/**,.pytest_cache/**,coverage.xml,tests/**
sonar.python.coverage.reportPaths=coverage.xml